language: ruby
rvm:
  - 2.0.0

env:
  - secret_token=thisisasecrettoken

script:
  - bundle exec rake default konacha:run

before_script:
  - psql -c 'create database wiki_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

notifications:
  email:
    - wikenso@nilenso.com