language: ruby
rvm:
- 2.0.0
env:
- secret_token=thisisasecrettoken ACTION_MAILER_HOST=wikensotest.com

script:
- bundle exec rake
- bundle exec rake konacha:run

before_script:
- psql -c 'create database wiki_test;' -U postgres
- cp config/database.yml.sample config/database.yml
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: iq+qZDYqRN7i+jHkzx1zTUjk6JUjBXPhsPtHI+PL3MqOPFeGXUjUVjWBCpWGctA39x7loDa5BUDWqmXC0plFleLRZ3yi5PXlDlaNICgqKw8gkGxggOchorobmzLJMYvaW9CeY9giVsLZb9tckpTvacxYdo90b5XXcuJ8tE8IPVk=
  app: wikenso-staging
  run: "rake db:migrate"
  on:
    repo: nilenso/wikenso
